image: gitpod/workspace-full

tasks:
  - name: Setup Flutter
    init: |
      # Install Flutter
      git clone https://github.com/flutter/flutter.git -b stable $HOME/flutter
      echo 'export PATH="$HOME/flutter/bin:$PATH"' >> $HOME/.bashrc
      source $HOME/.bashrc
      flutter config --enable-web
      flutter doctor
  - name: Install Android SDK
    init: |
      yes | sdkmanager --licenses
      flutter doctor

  - name: Run Flutter App
    command: flutter run -d web-server

vscode:
  extensions:
    - dart-code.flutter
