image: gitpod/workspace-full

tasks:
  - name: Install Flutter
    init: |
      git clone https://github.com/flutter/flutter.git -b stable $HOME/flutter
      echo 'export PATH="$HOME/flutter/bin:$PATH"' >> $HOME/.bashrc
      source $HOME/.bashrc
      flutter config --enable-web
      flutter doctor
  - name: Run Flutter App
    command: flutter run -d web-server

vscode:
  extensions:
    - dart-code.flutter
